#                       _
#   ___  _ __    _ __  | |_   ___   ___   _ _   __ _
#  (_-< | '  \  | '_ \ |  _| / -_) |___| | '_| / _` |
#  /__/ |_|_|_| | .__/  \__| \___|       |_|   \__,_|
#               |_|
tasks:
  - name:    cloggy
    before:  clogrc/gitpod/before-tasks.sh
    init:    clogrc/gitpod/init-tasks.sh
    command: clogrc/gitpod/startup-tasks.sh

# port for server & godoc
ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - dbaeumer.vscode-eslint            # lint javascript code
    - piersdeseilligny.betterfountain   # screen writer plugin
    - stkb.rewrap                       # wrap markdown at column boundaries
    - ms-toolsai.jupyter                # jupyter notebook support
    - mads-hartmann.bash-ide-vscode     # bash scripting helper
    - DotJoshJohnson.xml                # xml formatting xpath etc
